<?php
?>
<?php
$blog = $block->getBlog();
$tags = $blog['tags'];
$tags= explode (",", $tags);
?>
<div class="row">
    <div class="col-12">
        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <h1 class="fw-bolder mb-1"><?= $blog['name'] ?></h1>
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">Posted on <?= $blog['publish_date_from'] ?></div>
                <!-- Post categories-->
                <label class="font-weigth-bold">Tags: </label>
                <?php if($tags) : ?>
                    <?php foreach ($tags as $tag) : ?>
                        <a class="badge bg-secondary text-decoration-none link-light text-white" href="#!">
                            <?= $tag ?>
                        </a>
                    <?php  endforeach; ?>
                <?php  endif; ?>
            </header>
            <!-- Preview image figure-->
            <figure class="mb-4"><img class="img-fluid rounded" style="width: 100%" src="<?= $blog['thumbnail'] ?>" alt="..." /></figure>
            <!-- Post content-->
            <section class="mb-5">
                <div class="font-weight-bold"><?= $blog['short_description']?></div>
                <div><?= $blog['description'] ?></div>
            </section>
        </article>
    </div>
</div>
